### ISSUE TITLE
Premium: cannot run any BusyBox command

### ISSUE THREAD

**Issue by rjarry** [shiftrot/droidvim#10]
Hi I made a donation and just got the premium features.

Git works but all BusyBox commands fail with the same error:

```
RUNTIME=$APPEXTFILES/runtime             <
 $ export VIM=$APPEXTFILES
 $ ls
CANNOT LINK EXECUTABLE "ls": cannot locate symbol "OpenSSL_add_all_algorithms" referenced by "/system/lib64/libselinux.so"...
Aborted
 $ mkdir x
CANNOT LINK EXECUTABLE "mkdir": cannot locate symbol "OpenSSL_add_all_algorithms" referenced by "/system/lib64/libselinux.so"...
Aborted
```

**Comment by shiftrot** [comment]
Please try the following.

1. Update to the latest BETA version on Google Play.
2. See the following URL
https://droidterm-e8a40.firebaseapp.com/droidvim/#h52

I think that this problem is environment dependent issue.
If trying the above method does not solve the problem, please let me know about your environment such as Android version, model name, etc. (The output results of `getprop`and `printenv` are particularly useful.)
Sorry for your inconvenience.

**Comment by rjarry** [comment]
Hi thanks for your reply,

I don't know how to install the latest beta version on Google play.

I tried updating git and BusyBox, but it fails again:

```
 $ busybox-setup sysbin
add busybox commands...
add system/bin...
ls: /system/bin/uncrypt: Permission denied
add system/xbin...
 $
 $ ls
CANNOT LINK EXECUTABLE "ls": cannot locate symbol "OpenSSL_add_all_algorithms" referenced by "/system/lib64/libselinux.so"...
Aborted
 ```

Here is some additional info:

```
 $ busybox | head
BusyBox v1.25.1 (2017-04-10 11:15:07 DST) multi-call binary.
BusyBox is copyrighted by many authors between 1998-2015.
Licensed under GPLv2. See source distribution for detailed
```

[printenv.txt](https://github.com/shiftrot/droidvim/files/1670372/printenv.txt)
[getprop.txt](https://github.com/shiftrot/droidvim/files/1670373/getprop.txt)

**Comment by rjarry** [comment]
Just so you know, I changed the $HOME folder path to /sdcard and the commands now work fine.

I'm not sure I understand why, but I can live with this workaround.

Let me know if you have a proper fix. Cheers.

**Comment by shiftrot** [comment]
> I don't know how to install the latest beta version on Google play.

Scroll to the bottom.
There should be a section labeled "Become a beta tester"
I will update soon so please wait for a while if you can not try the beta version.

> Just so you know, I changed the $HOME folder path to /sdcard and the commands now work fine.

This problem can also occur when loading saved settings.
For this reason, in the beta version, if the value of "shell path" or "$HOME" is invalid, it will be changed to default value.

The "properly" solution is as follows.
1. Clear data via "AppInfo" -> "Storage" (without uninstall DroidVim)
2. Move to internal storage if the application is installed in external storage.
3. Launch the DroidVim.
4. Download git from "EXTRA" button.

Thanks!
