### ISSUE TITLE
Unable to access 'gpg' program

### ISSUE THREAD

**Issue by sibinpthomas** [shiftrot/droidvim#11]
Hi,

How can I access the 'gpg' program via DroidVim (in a similar way to curl or git)?
I tried installing gpg via Termux (https://play.google.com/store/apps/details?id=com.termux), however this installation seems to be in a sandbox which DroidVim can't access.

Is there a way I could make 'gpg' available to DroidVim?

**Comment by shiftrot** [comment]
I have no plans to add PGP to extra content for now.
Since the share intent has been added to the DroidVim beta on GooglePlay, it may be better to use a PGP app such as OpenKeychain via an intent.
