### ISSUE TITLE
Soft Ctrl key stops working with soft keyboard after using a hardware keyboard

### ISSUE THREAD

**Issue by Himura2la** [shiftrot/droidvim#12]
The behavior is the following (I use the character-based direct input)

1. Press Ctrl key on the function bar
2. The caret changes to triangular
3. Press any letter on a soft keyboard (e.g. r to redo)
4. Vim gets the r without Ctrl and replaces the current symbol with the next typed

I can provide any debugging info if you tell how to collect it

**Comment by Himura2la** [comment]
Android 6.0.1
Gboard
Russian
I found it more natural, the word-based method feels very strange, I'm not comfortable with it.

**Comment by shiftrot** [comment]
I fixed Ctrl key problem and improve Gboard hardware keyboard handling.
Please try beta version (Just scroll down the page of Play Store).

**Comment by Himura2la** [comment]
Wow, thanks for the efficiency, I'll try

**Comment by Himura2la** [comment]
It works! I think it's the quickest fix I've ever seen )
