### ISSUE TITLE
CTRL not working?

### ISSUE THREAD

**Issue by philiprhoades** [shiftrot/droidvim#13]
People,

I just found DroidVim - I'm excited!

Navigation keys are working but I can't jump to tags - I push CTRL first and then "J" but I get the normal cursor movement - what am I missing?

Thanks,
Phil.

**Comment by shiftrot** [comment]
It is normal behavior. See `:h Ctrl-J`. Jump to the definition is `Ctrl-]` .

**Comment by philiprhoades** [comment]
Yes, I just worked it out too - I had not used tags for a while and with the small text on the screen I was mis-reading the "]" as "J" . . sorry . .
I am really liking having Vim on Android!
Thanks.

**Comment by shiftrot** [comment]
Happy Vimming! 😉
