### ISSUE TITLE
Running DroidVim from the CL

### ISSUE THREAD

**Issue by philiprhoades** [shiftrot/droidvim#15]
People,

When I reporting a different issue:

https://github.com/shiftrot/droidvim/issues/14

on my old Galaxy Note 1, a problem I DID NOT have was running vim from the Command Line (ie connecting from my Linux box to the phone running sshDroid allowed me to use DV just like I was in an Xterm).  After being forced to get a new phone (Pixel 2XL), rooting etc etc and getting things back to where I was before, I now find that running DV from the CL does not work properly . . ie the cursor is at the bottom of the screen instead of the top and all text inserted appears on the bottom line.  Quitting out of the file works fine but the program is not usable obviously.

I am missing something again?

Thanks,
Phil.

**Comment by shiftrot** [comment]
If "Command Line" means sshDroid, ask the developer of sshDroid.
