### ISSUE TITLE
Inconsistent behavior of colorscheme between two runs

### ISSUE THREAD

**Issue by s-c-p** [shiftrot/droidvim#18]
Hi,

The solarized dark color is not consistent. As soon as I installed DroidVim, I activated the solarized dark colorscheme via the preferences menu, and opened a few files. I saw the beautiful colors as below:

![SML](https://i.imgur.com/i6ToJ6I.png)
![SQL](https://i.imgur.com/UxY193H.png)

Then, I quit the app via `:q` and now when I am opening the files I see an uglier version of solarized dark, like:

![SML](https://i.imgur.com/dGbeWIk.png)
![SQL](https://i.imgur.com/2ABIlvz.png)

I want the color combination shown in the first set of pictures but it is visible only during first run, all subsequent runs have the latter color combo.

I have seen this issue occur on Android 4.4 and 6.0

**Comment by shiftrot** [comment]
I confirm this issue and fixed it.
Sorry to trouble you, but please try out the beta version (just scroll down the page of PlayStore).
Or simply adding `set bg=light` to your .vimrc will fix the problem.

Thank you for the impeccable bug report!

**Comment by s-c-p** [comment]
Wow, that was fast. Thanks for making DroidVim.
