### ISSUE TITLE
invoking vim from a shell

### ISSUE THREAD

**Issue by mfrasca** [shiftrot/droidvim#19]
Assume I'm the so called "power user" or maybe an application developer, and that I want to use `vim` from `adb shell`. I sometimes need to change one or two characters in a text file, and I would not want to copy files back and forth between phone and desktop, only because I have no text editor on the phone.

### Expected behaviour
I would enter the phone via `adb shell` and invoke `vim` from the CLI.  Can I do this with `droidvim`?

Actually, I'm not really thinking of a physical phone: my use case is on a virtual machine.  How can I install `droidvim` in such a phone image?

**Comment by shiftrot** [comment]
It would be better to use Busybox vi.
For simple substitution, you can use cat and sed of toybox.

**Comment by mfrasca** [comment]
according to wikipedia, toybox is included in Android since version 6, so creating a 6-virtual machine would solve my problem.  I'll try. thank you, I had never heard of toybox I confess.

**Comment by mfrasca** [comment]
BTW: I had posted [a question on stackexchange](https://android.stackexchange.com/q/201657/273030), and you just answered it here (use toybox, included in Android 6).  maybe you have an account there and care to answer yourself?

**Comment by scarlion1** [comment]
The `vi` from _toybox_ is crap though!  The arrow keys will wipe out swaths of my lines, even in normal mode!  It also frequently crashes and it does save anything in a swap/recovery file, etc.

I got it running, with:
```
export PATH="/data/user/0/com.droidvim/files/bin:$PATH"
alias vi="LD_LIBRARY_PATH=/data/user/0/com.droidvim/files/usr/lib VIM=/data/user/0/com.droidvim/files VIMRUNTIME=/data/user/0/com.droidvim/files/runtime vim.default -u /data/user/0/com.droidvim/files/vimrc"
```
