### ISSUE TITLE
Release on fdroid

### ISSUE THREAD

**Issue by ghost** [shiftrot/droidvim#20]
what about releasing this app on f-droid?
Most vim users are fdroid users on phone.

**Comment by shiftrot** [comment]
I am sorry, but I am not planning to create an F-droid account now.

**Comment by ExtremeNerd** [comment]
I don't think very regular maintainance will be needed.
In the sense that most people who want to use vim on android use fdroid. Thus it is better to provide build scripts to fdroiddata repository. However, it should be free of google stuff.

**Comment by shiftrot** [comment]
Since there should be no problem with the license, I think that it would be better for you (or someone familiar with F-Droid) to do it.
In the first place, I think that F-Droid users who need Vim use Termux's Vim. DroidVim is just a terminal emulator customized for amateur users.

**Comment by yashpalgoyal1304** [comment]
> I am not planning to create an F-droid account now.

you dont need any fdroid or even ANY other account for that 😅

umh, can you look at this https://gitlab.com/fdroid/rfp/-/issues/1443#note_856506979 and give your final conclusive thought??
