### ISSUE TITLE
Can't see it in recent task

### ISSUE THREAD

**Issue by khejing** [shiftrot/droidvim#22]
Thanks for the great app, but I often use the Recents screen to switch task, when to Droidvim, I had to use the notification. It's a little inconvenient. So can it be fixed?

**Comment by shiftrot** [comment]
Is it your problem that history does not remain when DroidVim is launched by another application via intent?

It is a deliberate specification of the application that is the base of DroidVim, but it certainly is not a general, so I think I will fix it.

If not, please let me know the following.

1. Steps to reproduce your problem.
2. (If you don't know the steps) How often is the problem occurring?
3. Your Android version.
4. Your device name.

**Comment by khejing** [comment]
My use case is this: I use Total Commander to send my text file of note to Home, so I can just tap the icon to start Droidvim to edit my note. At the same time, I often open another app like Coursera to learn from it. So I often need to switch between the two app to make notes. But when I press the Recent Apps button, I can just see Coursera. The only way to return back to Droidvim is tapping its notification from the notification list.

I use Xiaomi max 2, my android version is 7.1.1

**Comment by shiftrot** [comment]
Android applications launch other applications via "Intent".
Droidvim called from other applications via "Intent" is set not to be displayed in Recent Apps. However, it will be changed in the next update or beta version (Scroll down the PlayStore page).

Until then please tap the DroidVim icon from the Android launcher (HOME app) once and display it on Recent Apps.
Sorry for your inconvenience.

**Comment by khejing** [comment]
Thank you very much for the explanation and the fix! I've already understood the reason. For now, I'll first tap DroidVim to open it, and then tap my file icon, it's ok.

Thanks again for your wonderful app!
