### ISSUE TITLE
cert.pem file missing

### ISSUE THREAD

**Issue by jdn06** [shiftrot/droidvim#25]
When I try to use extra package git, I have a problem since last update:

`fatal: unable to access 'https://github.com/my-repository': error setting certificate verify locations:
CAfile: /data/data/com.droidvim/files/usr/etc/tls/cert.pem
CApath: none`

I checked the path and this tls directory only contains an openssl.cnf file.
I tried to clean extra packages and install them again.
I also tried the busybox-setup commands I found on Droidvim site. Nothing changed.

**Comment by shiftrot** [comment]
I confirmed this problem and updated the file on the server.
I have confirmed that Arm (32/64 bit) works properly. For x86 (32/64 bit), it will be uploaded to the server in a few hours.
Sorry for your inconvenience.

**Comment by jdn06** [comment]
Problem solved for me. Thanks a lot !
