### ISSUE TITLE
Error E137: Viminfo file is not writable

### ISSUE THREAD

**Issue by ghistes** [shiftrot/droidvim#27]
Hi,

I have a strange issue resulting in the above error every time I write a file.

I have set my HOME to the directory /sdcard/mh. This is where both .vimrc and .viminfo reside.

When I delete the .viminfo file and edit a file a new .viminfo file is created in that directory without error, however whenever I edit a file with an existing .viminfo file the above Error appears - even though it seems to perfectly possible for droidvim to write to this file.

I have played around with various viminfo-settings in the .vimrc file but I cannot get rid of this error - what could be the problem here?

I am using version 1.1.65.

Many thanks!

**Comment by shiftrot** [comment]
Read the following help and update to the latest version.
https://droidterm-e8a40.firebaseapp.com/droidvim/#h43

If you still have problem, please contact again.

**Comment by ghistes** [comment]
I am currently using the lastest version from the Google playstore and can confirm that adding

set viminfo+=n$APPFILES/home/.viminfo

solves the problem (no more errors).

I assume that with this setting the .viminfo-file is no longer located in my $HOME directory, but in a directory where droidvim can change the file-attributes as it needs to.

So in efffect that means that it does not seem to be possible to have .viminfo and .vimrc in the same directory when you set $HOME to some arbitary directory as you then run into the above error.

But the solution is absolutely good enough for me - many thanks!
