### ISSUE TITLE
Accessing help results in tag not found

### ISSUE THREAD

**Issue by grechaw** [shiftrot/droidvim#29]
Hello, I've got a very curious issue.  It's probably not a bug in droidvim but I thought you may have seen it before.  So if there's any workaround you can suggest I'll be very happy to take it.   The issue is that, on my old android device, I cannot access vim help.

Here is the symptom

```
:he 
E426:tag not found: help.txt@en
```

This message is returned for any legitimate help topic:

```
:he vimwiki
E426: tag not found: vimwiki@en
```

However, the tag files are all good and you can tell when you search for some other topic

```
:he asdf
E149: Sorry, no help for asdf
```

I can run helptags fine and it does regenerate.  My runtime paths are all good, and I'm happy to provide more info if you have capacity to help.  Here's the kicker....

This old phone is running Android OS 4.4.4 and I cannot upgrade it.
I've created a basic emulator running 4.4.4, built and ran droid vim on it, and the help system is fine on the emulator.  So I think it might be about my specific phone.  It is an old Motorola Droid Mini, which is different from some phones in having no sd card.

Anyhow, thanks for reading, if you have suggestions or things I should try I'm all ears.  I just love this app and having a full-functioning vim is a goal.  I'm also interested in enhancing it (with dropbear) so I'd be happy to take instructions for trying out things with the build (tho a lot of this android stuff is new to me).

**Comment by shiftrot** [comment]
First of all, please check if the problem occurs with a clean installation (uninstall → reinstall is most preferable).

If you have problems in a clean environment, copy the environment variables to the clipboard with the following command and paste them on this page.
1. r! set
2. ggyGgY

Sorry for your inconvenience.

> I'm also interested in enhancing it (with dropbear) so I'd be happy to take instructions for trying out things with the build (tho a lot of this android stuff is new to me).

It's not directly related to DroidVim, so ask a question in another community.
There are several projects that distribute dropbear for Android 4.4.

**Comment by grechaw** [comment]
Thank you @shiftrot a re-install did indeed help.  If re-enabling my plugins messes things up then I'll know it's my problem.

**Comment by grechaw** [comment]
OK I've dug a bit more @shiftrot and think there's still some kind of issue.

Here's how to reproduce on a fresh install:

Install and start
ctrl-z into home directory
touch .vimrc

now the issue appears.  So a vimrc file, even with nothing in it, is overriding something important to the application?  I'll try to work around this, but maybe you can repro now too.

**Comment by grechaw** [comment]
Oh, forget it, I cannot reproduce on a fresh emulator the way I put it.  I'll troubleshoot my environment and submit a new issue if I can isolate the problem.

**Comment by grechaw** [comment]
This was my issue -- to view help one must "set ignorecase"

**Comment by benhormann** [comment]
The problem is with Vim's binary tag search. [:help 'tagbsearch'](https://vimhelp.org/options.txt.html#%27tagbsearch%27)
Workaround: `set notagbsearch`

I have set noignorecase in my vimrc, so explicitly disabling tbs works for me.
