### ISSUE TITLE
premium (git, curl, busybox) re-install

### ISSUE THREAD

**Issue by sessyargc** [shiftrot/droidvim#3]
Thanks for creating DroidVim. I made a donation and got the extra features.

I have the extra features in one phone (main use phone), but I have another phone (rooted) where I also want the extra features to be enabled. On the 2nd phone it does not allow me to donate again saying that I already own the app ... but there is also no way to download just the extra binaries.

**Comment by sessyargc** [comment]
Uninstall -> Re-install -> then press Extra again will download the extra features.

**Comment by shiftrot** [comment]
I confirmed this issue. I solved it by following the steps below
1. Settings -> Apps -> Google Play Store -> Clear Cache
2. Execute DroidVim via "OPEN" button on PlayStore.

But I think that the reliable way is your way.
JFYI. Thanks.
