### ISSUE TITLE
Issue while using Hacker's Keyboard with DroidVim!

### ISSUE THREAD

**Issue by KingRanger984** [shiftrot/droidvim#30]
Hi Dev,

I really like your app. I love Vim so I installed this app on my phone. I am not really habitual of using H,J,K & L keys for controlling the cursor(I know it's quite odd for a daily vim user) so I use the arrow keys on my Laptop with vim. On my phone, in order to do the same, I have to use Hacker's Keyboard. Now when I press arrow keys, they start printing as text like A, B etc even when I am out of Insert Mode (when I press the arrow keys, the app enters insert mode itself which is odd). Please Fix this Issue ASAP!

Thank You!

**Comment by shiftrot** [comment]
1. Try a web search for "Vim abcd".
2. Check if the problem occurs in a clean environment (uninstall-> Re-install).

If the problem occurs in a clean environment, please let me know:
+ Android version.
+ Device name.
AFIK it works properly.

**Comment by KingRanger984** [comment]
Ok, I got the solution here - https://stackoverflow.com/a/16858267/11808775
BTW You should add this to the .vimrc file - set nocompatible
This would help users like me!

**Comment by KingRanger984** [comment]
For a while, what I did above worked well. Now the issue still persists!

Here's my device info-
Android - 8 Oreo
Device - Redmi Note 5
Manufacturer - Redmi Xiaomi

**Comment by shiftrot** [comment]
I'm not sure what you are saying.
If it works, even temporarily, then your problem is caused by the settings or plugins you are using. You can't solve it without telling me which settings or plugins are the cause.
After startup, it is recommended to execute `:set compatible?` to check the current status.

Using an emulator and some real devices, we have confirmed that DroidVim and Hacker's keyboard work properly on all Android versions.

Read the help. (:h defaults.vim)
```
This should work well for new Vim users.  If you create your own .vimrc, it is
recommended to add these lines somewhere near the top: >
	unlet! skip_defaults_vim
	source $VIMRUNTIME/defaults.vim
```

`set nocompatible` should be set on all Vim, regardless of DroidVim.

**Comment by shiftrot** [comment]
Please let me know if it works in a clean environment (Uninstall-> Re-install, without adding user vimrc and plugin). If it is not working properly, please tell me the result of `:set compatible?`.

**Comment by KingRanger984** [comment]
Ok I have uninstalled and reinstalled DroidVim. The output of `:set compatible?` is `nocompatible`

**Comment by KingRanger984** [comment]
Ok I have researched a bit more and it looks like an issue with the terminal type. As soon as I had installed DroidVim, I changed terminal to "linux" (Preferences -> Shell -> Terminal). But when I switched the terminal back to screen-256color
