### ISSUE TITLE
segmentation fault on android 10

### ISSUE THREAD

**Issue by zqb-all** [shiftrot/droidvim#31]
![Screenshot_20200223_001559](https://user-images.githubusercontent.com/21177884/75095807-d9472400-55d3-11ea-83bb-e985eb04049a.jpg)

the app can not work after update to android 10.

device: huawei p30
android version: 10

I love this app, any advices for me to make it work again?

**Comment by shiftrot** [comment]
I have confirmed that DroidVim works properly on Android 10 and R.

Please update DroidVim to the latest version first.
If you are still having problems, try the following:

DroidVim can save app preferences and restore. (User vimrc and plugins are lost)
1. Does the problem occur in a clean (Uninstall->Reinstall) environment ?
2. Does the problem occur even after restoring the app preferences?

**Comment by zqb-all** [comment]
> Does the problem occur in a clean (Uninstall->Reinstall) environment ?

yes，I uninstall then reinstall it from google play more then 3 times,  problem still there.
I try all the setting in "TROUBLESHOOTING", still segmentation fault.
Then I try beta version in google play, same problem.

now I can use bash after the vim segmentation fault, if you want some information that can get from this bash, please let me know

**Comment by shiftrot** [comment]
Could you let me know the following information?
Shut down and restart your device (P30), just in case.
### Execute following commands in the shell:
1. vim
2. vim -u NORC -N
3. vim -u NONE -N
4. getprop
5. set
6. ls $APPLIB
7. $APPFILES/usr/bin/busybox
8. exit
9. vim
10. vim -u NORC -N
11. vim -u NONE -N

An error may be displayed depending on the command, but ignore it.

### Copy result to clipboard:
1. Long press on screen (Popup Menu)
2. Choose "Screen" (not "Clipboard") -> "Copy screen text" -> "Screen buffer"
Paste it on this page or email me.

### Library name:
1. Long press on screen (Popup Menu)
2. Choose "Preferences" -> "Shell" -> "Change system library".
3. Let me know the library name displayed in "Current Library"

Sorry for your inconvenience.

**Comment by zqb-all** [comment]
Glad to do that, please check the email : )

**Comment by shiftrot** [comment]
Thank you for sending device data.
Please try beta and let me know if it worked.

> Current Library is arm64, I try to change to arm32, vim still now work.

Is it a "vim still NOT work." typo?

**Comment by zqb-all** [comment]
> Is it a "vim still NOT work." typo?

Oh,  sorry for the typo.  yes, arm32 library not work.

> Please try beta and let me know if it worked.

You mean the beta version from Play Store ?
I just reinstall it, still segmentation fault.
Play Store show that `"last updated 21 Feb 2020"`, it's that the right version to try ?

![vim](https://user-images.githubusercontent.com/21177884/75351910-d86c0600-58e3-11ea-8f13-9bd4d6e34d1f.jpg)

**Comment by shiftrot** [comment]
I think it's due to the slow PlayStore review.

Please try internal test version of DroidVim. (1.5.0-DEV-proot)
https://play.google.com/apps/internaltest/4698173595896608727
!!! Uninstall the beta version before installing the internal test version.
If zhua****@gmail.com is not your GooglePlay account, please let me know your GooglePlay account email address to invite.

**Comment by zqb-all** [comment]
Thanks. zhua****@gmail.com is my GooglePlay account.

> https://play.google.com/apps/internaltest/4698173595896608727

But this url just show a link to PlayStore, and PlayStore still is version `21 Feb 2020` .
I will check that tomorrow.

**Comment by shiftrot** [comment]
You should see the same opt-in / opt-out screen as in the beta. Could you try it again on the android device?
https://play.google.com/apps/internaltest/4698173595896608727

If that doesn't work, try the links below.
https://appdistribution.firebase.dev/i/skdysQyt

**Comment by zqb-all** [comment]
Now I can get the new version from PlayStore, I try uninstall->restart device->install, it crash on my device.
Then I unistall it and try the app from `https://appdistribution.firebase.dev/i/skdysQyt`, the same crash.
Also I try the Troubleshooting, not work.

Now crash just popup a window `"Sorry, Vim has crashed"`, but did not show `"Segmentation fault"` or any other information on bash.

**Comment by zqb-all** [comment]
Cool!  I just reveive `DroidVim 1.5.0-DEV-bin64 (237)`, it works!
Thank you : )

**Comment by shiftrot** [comment]
That means the problem is on the P30 side, not on DroidVim. There are probably other apps that do not work properly. If you can, please report to Huawei customer support that "applications using 32-bit binaries do not work".

I'd like to try some, can you help me a bit more.

**Comment by zqb-all** [comment]
>  If you can, please report to Huawei customer support that "applications using 32-bit binaries do not work".

OK

> I'd like to try some, can you help me a bit more.

Sure, I am glad to do that. Send me new version and I will try it.

**Comment by shiftrot** [comment]
I have uploaded version 1.5.0. Release Candidate.
If you do not have any problems with 1.5.0, please use the beta version of PlayStore. The same version has been uploaded as beta.
Thank you😉

**Comment by zqb-all** [comment]
OK, I get version 1.5.0 from App Tester, now it works good.
When PlatStore finish the review and show this beta version to me, I will try it.

**Comment by zqb-all** [comment]
Beta version of PlayStore works good.

**Comment by shiftrot** [comment]
If the beta released today works properly, it will be officially released next week.
Thank you.
