### ISSUE TITLE
a new file always gets .txt extension

### ISSUE THREAD

**Issue by zveber** [shiftrot/droidvim#32]
A new file always gets `.txt` extension. For example you can do these steps:
1. Do a long tap
2. In the menu choose Storage->Storage->Create file
3. Type custom name, for example `test.py`
4. Type `:ls` as a command. You'll see that the file name is `test.py.txt`

**Comment by shiftrot** [comment]
It probably depends on the version of Android and will be fixed in the next release.
However, the beta release seems to take more than 7-10 days, as Google's review has been delayed due to the coronavirus.
If you are in a hurry, please send your email address to shiftrot@gmail.com.
Thanks.

**Comment by shiftrot** [comment]
The latest version (1.5.2) has been released. If you still have problems, please contact again.
