### ISSUE TITLE
Could you provide a the option to turn syntax highlighting off

### ISSUE THREAD

**Issue by 14u2ponder** [shiftrot/droidvim#33]
Some of us don't like syntax highlighting.
Also another good thing would give us the option not to set numbers. Both should be easy to comment out in vimrc.

**Comment by shiftrot** [comment]
Use vimrc to set options for Vim.
"Long press menu" > "Edit .vimrc"
or
`:e ~/.vimrc`

**Comment by 14u2ponder** [comment]
Cool thanks.
