### ISSUE TITLE
Where can I find ATE-mod-clipboard.vim?

### ISSUE THREAD

**Issue by filbranden** [shiftrot/droidvim#34]
Hi! Thanks for DroidVim, it's really awesome and I love it! I frequently use it to quickly prototype Vim functions and answer questions on [Vi & Vim StackExchange](https://vi.stackexchange.com/). And with Python + Git support on the premium version I can even get UltiSnips working through vim-plug, yay!

I have one question about the clipboard scripts, such as `ATE-mod-clipboard.vim`. Where do the scripts come from? Can I find a source repository or vim-scripts page for them? The files I find under `$VIMRUNTIME/plugin/ATE-*.vim` don't seem to have any comments or headers. I didn't really find any files with such names in this repository and a Google search for the file names or function names didn't help much either...

I find the copy & paste behavior sometimes to be a bit awkward, so I was wondering if I could consider perhaps writing some fixes where possible and potentially contributing those to the upstream that is used to build this app?

Thanks again for building a wonderful product!

**Comment by shiftrot** [comment]
The Vim script for DroidVim is zipped in the following location. (/term/src/vim/res/raw)
https://github.com/shiftrot/droidvim/blob/master/term/src/vim/res/raw/runtime_extra.zip
These scripts only work with DroidVim and I wrote them.

The script only exchanges strings through the file, so please let me know if you run into any problems that the script cannot solve.
After fixing the bug, pasting the modified script file without creating a PR is fine.

Thank you for your kindness.
