### ISSUE TITLE
No support for plugin managers

### ISSUE THREAD

**Issue by xslendix** [shiftrot/droidvim#35]
I am trying to use vim-plug as my plugin manager but I need git installed. A binary of git included in the app would fix the issue. Thats all.

**Comment by Snaptags** [comment]
You can get git support as an in-app purchase.

**Comment by xslendix** [comment]
cant purchase stuff since i dont use the play store, so ill cross compile it i guess

**Comment by shiftrot** [comment]
If you can't use Google Play, I recommend using Termux.

About cross compilation:
Git can also be cross-compiled using the Android NDK only.
It is easier to use the Termux build system if you can set the environment variables correctly.

**Comment by xslendix** [comment]
Yeah but my experience with termux and the nethunter terminal for example were pretty bad

**Comment by shiftrot** [comment]
https://droidterm-e8a40.firebaseapp.com/droidvim/#t5
If you don't need python, there is a way to manage vimfiles with Termux and copy or symlink it to DroidVim's home.

**Comment by TheJoeSchr** [comment]
If I purchase git support, does this work then with plug.vim if I put it into autoload?

**Comment by shiftrot** [comment]
I have not used it, but there are reports of it working.
