### ISSUE TITLE
Vim not starting 

### ISSUE THREAD

**Issue by shadmansaleh** [shiftrot/droidvim#37]
No binary is getting executed . I am getting permission denied for  all binaries . The binaries have execution permission (I've tried chmod +x ).

> Just noticed you are targeting android 11 (api 30).

Probably you don't know from android 10(or from any app targeting API 29) apps cannot execute native binaries in data directory of that app (/data/data/PACKAGE_NAME/) . Native binaries are only allowed in lib folder(/data/lib/PACKAGE_NAME symlinked to /data/data/PACKAGE_NAME/lib) .

I think thats the reason I'm getting all those permission denied . Can you take a look at when you have time . 

This is what I see when I open the app

![Screenshot_20200901-162728_DroidVim](https://user-images.githubusercontent.com/13149513/91838978-28030400-ec70-11ea-9764-f62fcef63f08.jpg)

Device model : Samsung galaxy M20
Android version : Android 10
I belive it's a arm64 device

**Comment by shiftrot** [comment]
If you have installed the app in the external storage (SD card), please move the app to the internal storage.
Then use system recovery or clear the storage from the Android's app info and start the application.
If installed on internal storage, all executables will be created as symbolic links to native libraries.

If it still does not work, please let me know about the following execution results.

```
ls -l $APPFILES/bin
ls -l $APPLIB/libbusybox.so
cd $HOME
ln -s $APPLIB/libbusybox.so busybox
./busybox
```
The execution result can also be copied by "Long press menu"> "Screen"> "Copy screen buffer".

DroidVim also uses proot, so it works on many Android 10+ devices without symlinks.
If proot doesn't work for your device, it may be improved by not using it.
If you could, install the beta version (scroll down the Play Store page) and try creating a file named "$APPFILES/proot.disable".

**Comment by shadmansaleh** [comment]
Installing the app on internal storage worked . I had prefared install location set to external storage . Thanks for the help.

Since being on external storage breaks the app why not set android:installLocation="internalOnly" in AndroidManifest.xml insted of auto . I think that's suppose to make the app  always get instslled on internal storage .

**Comment by shiftrot** [comment]
> Since being on external storage breaks the app why not set android:installLocation="internalOnly" in AndroidManifest.xml insted of auto . I think that's suppose to make the app always get instslled on internal storage .

Because DroidVim works on many devices even if installed on external storage.
Losing users to solve exceptional user problems is not what I want.

Your solution makes it impossible to update DroidVim installed on external storage (It looks like a DroidVim's bug).
It completely solves a few user's problems, but brings the complaints or 1 star of many users who have installed DroidVim on their external storage.
Since most users forget or don't understand how an external storage installation works.

DroidVim will display a message if the app is installed on external storage. Your issue was due to your device's internal and external storage using the same path.

I would appreciate if you could run ":e $APPFILES/exec.ok" with Vim to see if the file exists.

**Comment by shadmansaleh** [comment]
I can understand your situation . $APPFILES/exec.ok exists it has Hello World! in it .

**Comment by shadmansaleh** [comment]
I can understand your situation . $APPFILES/exec.ok exists it has Hello World! in it .

**Comment by shadmansaleh** [comment]
I can understand your situation . $APPFILES/exec.ok exists it has Hello World! in it .

**Comment by shadmansaleh** [comment]
I can understand your situation . $APPFILES/exec.ok exists it has Hello World! in it .

**Comment by shadmansaleh** [comment]
I can understand your situation . $APPFILES/exec.ok exists it has Hello World! in it .

**Comment by shadmansaleh** [comment]
I can understand your situation . $APPFILES/exec.ok exists it has Hello World! in it .

**Comment by shadmansaleh** [comment]
The files in $APPLIB have permission 611(-rw-r--r--) and are owned by 'system'  when the app is installed on external storage . Thats why the permission denied occurs.

**Comment by shadmansaleh** [comment]
I'm wondering if those native libraries are accessable through JNI when they are in external storage . I don't really know how JNI loads native codes. What do you think are other apps fine with this because they are accessing them through JNI?

**Comment by shiftrot** [comment]
Device manufacturers are free to change the location or permissions of the native library files as long as the Android API is working as designed.
DroidVim bypasses the Android API and directly accesses the Linux shell to run Vim. DroidVim is not strictly an Android app.

> $APPFILES/exec.ok exists it has Hello World! in it .

This means that on Android 10+, files can be executed in locations other than the native library directory.
If you're interested, try using git or python with in-app purchases. (or create shell script file in $HOME.)

**Comment by shadmansaleh** [comment]
yes execution on HOME works . I can basically put the app in external storage copy the libraries in home and remake the symliks to make it work . You can close thia issue
