### ISSUE TITLE
unable to start vim and git

### ISSUE THREAD

**Issue by ZSaberLv0** [shiftrot/droidvim#38]
env and main purpose:

* as some well known reason in China, I can not use Google Play, so I use `VMOS Pro` (an Android emulator on Android) to use Google Play to download DroidVim and purchase `git`

the issue:
![image](https://user-images.githubusercontent.com/6846867/101561373-33e52b80-3a00-11eb-9ff0-b3120de94969.png)

PS: any other way to obtain the `git` ?

**Comment by shiftrot** [comment]
It's not a Git issue. (terminfo issue)

1. Uninstall DroidVim and then reinstall DroidVim
2. Make sure that DroidVim starts properly.
3. Install Git

If you have any problems, please let me know:

* Result of the following commands.
1. echo $TERMINFO
2. ls $TERMINFO

* Your environment.
1. DroidVim version
2. Emulated Android Version (5.1.1?)
3. Your Android Device

**Comment by ZSaberLv0** [comment]
> It's not a Git issue. (terminfo issue)
> 
> 1. Uninstall DroidVim and then reinstall DroidVim
> 2. Make sure that DroidVim starts properly.

yes, it seems not git issue, just step 2 can not starts properly


![image](https://user-images.githubusercontent.com/6846867/101607998-2c457700-3a40-11eb-880e-f9df6ebae441.png)

1. DroidVim version: `2.0.5+DFM`, version code should be `290`
1. Emulated Android Version: `7.1.2`
1. Android Device: `RedMi K20 Pro` with `LineageOS 17.1`

PS:

* DroidVim(free version) works well with Android Device

**Comment by shiftrot** [comment]
Try following and restart:
```
chmod 666 $TERMINFO/s/screen-256color
```
> DroidVim(free version) works well with Android Device

The only difference is the file distribution format.
VMOS Pro may not handle the Google Play AAB format properly and the shell may not have (virtual) root privileges.
(By default, terminfo files only allow reading and writing from the root. So cannot open termcap file.)

**Comment by shiftrot** [comment]
Please let me know the result of the following:

1. whoami
2. ls -l $TERMINFO/usr/share/terminfo/s/screen-256color
3. cp $TERMINFO/usr/share/terminfo/s/screen-256color $HOME/test

According to your screenshot, there are two users, "generic_arm64" and "u0_a49" , which seems to be a problem.
It may work if all files are owned by the same owner.
```
chown -R -h  generic_arm64:generic_arm64 $APPFILES
```
In any case, I think this problem is difficult to solve from the app side.

**Comment by ZSaberLv0** [comment]
* steps: clear data of DroidVim in system setting => reopen DroidVim

    ![image](https://user-images.githubusercontent.com/6846867/101708342-02379780-3ac8-11eb-9155-e8facfeacfe6.png)

* steps: force close and reopen DroidVim

    ![image](https://user-images.githubusercontent.com/6846867/101708838-129c4200-3ac9-11eb-9e09-2e7c535aa990.png)


PS:
* close the issue since it's not a common case to use in emulated env, and I'm not sure whether it's `VMOS`'s problem
* copy contents of DroidVim to my Android device and modify some symlinks, the git seems works
    * sorry for the hack, if it's illegal, please let me know
    * hope to have other purchase method
