### ISSUE TITLE
constant messages after updating to 2.2.1+DFM

### ISSUE THREAD

**Issue by zveber** [shiftrot/droidvim#40]
Try to open some file with the app from a file manageror start the app and push `u` (undo). You will see a message "push enter or enter a commamd to continue". It annoys.

**Comment by shiftrot** [comment]
See `:help messages` or `:help shortmess`.
This is probably a Vim version dependent issue (not DroidVim).
If it only happens in a particular file, make sure it doesn't include the Vim mode line.

**Comment by zveber** [comment]
I've found out how to walk around the problem. For some reason I have to use big fonts. So I configured DroidVim to use 21 font suze. If I configure it to something smaller (20 for examle) the problem disappears. 
So maybe the problem should be closed. There are many problems with big fonts in different Android apps and maybe it is because Android itself.
