### ISSUE TITLE
cursor changes it's form after turning off and on screen

### ISSUE THREAD

**Issue by zveber** [shiftrot/droidvim#42]
To reproduce:
1. launch the app;
2. switch to insert mode with key `i`, cursor will change it's form from rectangle to line;
3. turn off screen with power button and unlock your phone, cursor's shape changes back to rectangle though the app is still in insert mode.

Replace mode (key `R`) has the same problem.

Version: 2.2.1+DFM.

**Comment by shiftrot** [comment]
I have confirmed this issue. Please wait for the next update.
Thanks!
