### ISSUE TITLE
new to Android (not vi) - a manual?

### ISSUE THREAD

**Issue by petercwallis** [shiftrot/droidvim#43]
droidvim does everything as expected except save files.  Vim was explicitly about editing files, but the files seem to have disappeared on Android.  What is the alternative?  Perhaps a "how to" on the front page for people who already use vim might be useful.

The version of android I am using may be the issue but surely, surely, if there is a thing called "Files" on the "desktop" it opens something that is default standard?  Droidvim is not going to the same place.  Is this a possible fix?

It is possible the android notion of "File" is an appropriation and there is no point thinking of files unless I have "rooted" the system. I only wanted to create a local html page that the browser could find and perhaps that is not possible either. If this is the case, a pointer in a "how to" would be useful.

**Comment by shiftrot** [comment]
Read about DroidVim and Android storage below.
https://droidterm-e8a40.firebaseapp.com/droidvim/#t4

Then download a file manager app from Google Play and see the Android directory structure and files. For Android 7 and later, you can also use the ”File Manager" button in the drawer on the left side of DroidVim. (If you don't see the internal storage, change the options in the 3-dot menu)

You can use the "Open File" button in the left drawer of DroidVim to open all files allowed on Android. If you want to create a new file in the external storage, use the "Storage" button or a file manager app.

> The version of android I am using may be the issue but surely, surely, if there is a thing called "Files" on the "desktop" it opens something that is default standard?  Droidvim is not going to the same place.  Is this a possible fix?

I'm not sure what you mean by "desktop". Do you mean the home screen?

> It is possible the android notion of "File" is an appropriation and there is no point thinking of files unless I have "rooted" the system. I only wanted to create a local html page that the browser could find and perhaps that is not possible either. If this is the case, a pointer in a "how to" would be useful.

After editing the HTML file, you can preview the HTML using "Long Press Menu" -> "Share..." -> "File".

**Comment by petercwallis** [comment]
Thanks shiftrot, That is exactly what I needed to know.  Perhaps it could go on the Github introductory page under <h2>New to Android</h2>?
