### ISSUE TITLE
I want a button to do ...

### ISSUE THREAD

**Issue by petercwallis** [shiftrot/droidvim#44]
As I understand it, android makes files belong to apps, not users.  Rather than the user being untrustworthy (as in the early days of unix where a computer was shared between lots of students) the user is trusted and the apps are possibly manevolent.  Rather than vim being there to let a trusted user edit any file, Droid Vim has a bunch of files it is allowed to edit.  The model is then to "share" those files with other apps.  Fine.  I have found how to add a button to the "menu extras" tray that will "share" with juiceSSH, but that juiceSSH doesn't do what I want (scp).

However, It seems I can also write bit of shell script that DroidVim can execute? Is there a way to make DroidVim offer my script as a button in the "Menu extra" (sic) tray?  It would need a variable to represent the name of the current vim file...

There may be a proper android app for scp but I can't find it and in any case, generic shell scirpt would seem more useful for anyone likely to use vi

**Comment by shiftrot** [comment]
I think you should use UserLAnd or Termux (F-Droid).

**Comment by petercwallis** [comment]
These are both ways of running linux on android and sure I can do that.  But could we have a way to add a button to the left hand tray that uses public  key encryption to copy what I have just written in vim to a cloud service running on a linux machine? (like I can do from UserLAnd using scp).

**Comment by shiftrot** [comment]
See below if you want a button to execute any command
Preferences> Function bar> Function key (F1-F12)
