### ISSUE TITLE
please make droidemacs! (very complex request)

### ISSUE THREAD

**Issue by cauerego** [shiftrot/droidvim#45]
https://www.reddit.com/r/linux4noobs/comments/ofrf6d/comment/h4fyrcz

and while you're at it, do it AGPL! 😁
https://www.reddit.com/r/startups/comments/ikjatj/does_licensing_your_product_under_agpl_prevent/

because termux.
https://t.me/offtopictermuxgroup/33877

don't call me crazy!! http://ahoxus.org/~cregox

**Comment by shiftrot** [comment]
Sorry, I don't use Emacs, and I have no plans to port Emacs to Android.

**Comment by cauerego** [comment]
fair enough.

but you should consider it... 😏
