### ISSUE TITLE
why isn't droidvim on fdroid?

### ISSUE THREAD

**Issue by CodeCubeNeo** [shiftrot/droidvim#46]
Hello. I was wondering if you could add your awesome app to fdroid, since that is (usually) the preffered way for installing open source apps on android, not through the proprietary playstore. Unless there is some kind of an issue with the fdroid requierments. But otherwise it will be well appreciated

**Comment by shiftrot** [comment]
Ubuntu is required to build Vim and grep binaries. (Probably not expected in F-Droid).
Another major reason is that I don't use F-Droid, so I don't really feel the need to use it.
