### ISSUE TITLE
copied text shouldn't have a new line character at the end

### ISSUE THREAD

**Issue by zveber** [shiftrot/droidvim#47]
To reproduce do this:
1. Start the app.
2. Write some text in it.
3. Do a long tap, choose _Share_, then _current buffer_ in the menu and choose _copy_ in the dialogue.
4. Paste the the text in any other app (*Google Keep* or *Google Docs* for example) and you will see that there is a new line after pasted text though it shouldn't be here.

There is the same problem if you copy selected text instead of whole buffer.

App version is 2.2.6+DFM.

**Comment by shiftrot** [comment]
New line at the end in buffer sharing is the correct behavior.
Try using xxd to switch to binary display.
Otherwise, the trailing newline depends on the Android version and the device manufacturer's implementation.

**Comment by zveber** [comment]
Oh, I see... Is there a simple way to copy a text to buffer without sharing it?

**Comment by shiftrot** [comment]
You can use the Vim command.
(See "Long press menu > Clipboard.")

**Comment by zveber** [comment]
I've found exactly what need in ’Menu -> Visual selection’, thank you for explanation.
