### ISSUE TITLE
`smartcase` isn't working

### ISSUE THREAD

**Issue by beelzebielsk** [shiftrot/droidvim#53]
Despite having `smartcase` set, search is still case sensitive, even when I never type a capital letter. `ignorecase` works as a temporary substitute but I prefer `smartcase`.

I've tested this out on two devices one running Android 10, another running 5.1.1. Both are running DroidVim version 2.2.6+DFM.

Lemme know if there's additional info you want.

**Comment by beelzebielsk** [comment]
Update: it works when I use the default rc file, and still works when I source my own rc file from there. But I'd prefer it just work without doing that. I have a temporary solution, tho.

**Comment by shiftrot** [comment]
This is not a bug.
`:help smartcase`
`:help /ignorecase`
