### ISSUE TITLE
Add ssh support

### ISSUE THREAD

**Issue by bsde1234** [shiftrot/droidvim#57]

**Comment by shiftrot** [comment]
Please let me know why you need ssh.
When accessing Github, it is recommended that you use an access token.

**Comment by bsde1234** [comment]
I mean in terminal I could use ssh to access some online servers like aws.

**Comment by bsde1234** [comment]
means add openssh client in busybox

**Comment by shiftrot** [comment]
If you need a Unix environment in addition to Vim, I recommend using another terminal emulator app.
SSH may be added during a major update, but there are no plans to add it soon.
