### ISSUE TITLE
Provide support for features of upstream vim version 9.0

### ISSUE THREAD

**Issue by Amazingkenneth** [shiftrot/droidvim#59]
Since June 28, 2022, [the major release 9.0](https://github.com/vim/vim/tags?after=v9.0.0010) of vim has been published. Vim 9 had made progress with better and faster vim script, user experience and many other features. As a Vim clone for Android, droidvim should follow up with upstream version iterations.

**Comment by shiftrot** [comment]
Updates will be coming soon.
The Vim version of DroidVim is 8.2.4804, so all Vim9 features are implemented.
