### ISSUE TITLE
Deleted characters may not have been deleted

### ISSUE THREAD

**Issue by highmtworks** [shiftrot/droidvim#63]
steps to reproduce:
* create a file (say 'file1.txt') in the internal storage Documents folder.
* let 'file1.txt' have 1030 bytes of content (using DroidVim or other editors).
* open 'file1.txt' from the drawer menu for editing in DroidVim.
* delete the last 30 bytes and `:w` then `:bd`.
* open again 'file1.txt' from the drawer menu,
  and see the deleted characters resurrect.

expected behavior:
* deleted characters remain deleted.

actual behavior:
* apparently deleted characters are not deleted.

version:
2.4.2+DFM

guess:
https://github.com/shiftrot/droidvim/blob/7e65c32b17/term/src/main/java/jackpal/androidterm/SyncFileObserver.java#L546
I suspect that 'w' does not truncate a file to a new content length.

**Comment by highmtworks** [comment]
Thank you for the fix and sorry for my missing environment information.

> the OS version of your device

Android 11

**Comment by highmtworks** [comment]
2.4.3+DFM from the play store works fine !

**Comment by shiftrot** [comment]
Thank you too!
