### ISSUE TITLE
.vimrc config file default location change for easy backup

### ISSUE THREAD

**Issue by andrew-ysk** [shiftrot/droidvim#68]
Ever since my android upgraded from ver 8 to ver.10, I have no longer access to $INTERNAL_STORAGE/android/data/com.droidvim/ folder to access the .vimrc file to backup to laptop via rsync. 

Can you make it or is there way to change the default location of .vimrc  to other folder (my sync folder), so everytime i do sync of the folder, the .vimrc can be backup periodically onto my pc. 

Thanks

**Comment by shiftrot** [comment]
Try recreating the symbolic link.
https://droidterm-e8a40.firebaseapp.com/droidvim/#h40
https://droidterm-e8a40.firebaseapp.com/droidvim/#t5
