### ISSUE TITLE
how do you automate system clipboard / register ( @* ) ?

### ISSUE THREAD

**Issue by m2habert** [shiftrot/droidvim#69]
I'd like to map a series of actions to a single mapping that would end with the yanking of a specific string to make it available for the global/OS clipboard.

Of course, manually the user can yank through the `"*yy` button.

But mapping a key combination  to visual-select + yank  like `V"*y` does not work.

Also, if I try `:let @* = @+` it returns an error.

¿Is there a work out? 

Thanks

**Comment by shiftrot** [comment]
You should use `map` instead of `noremap`.
```vim
nmap gy V"*yy
```
DroidVim uses the CUI version of Vim, so there is no clipboard register.
Clipboard commands are implemented with Vim scripts.

**Comment by m2habert** [comment]
thanks, man, appreciate it.
