### ISSUE TITLE
FR: Function bar: Switch character/word based input

### ISSUE THREAD

**Issue by tomtom** [shiftrot/droidvim#7]
Hi!

If users want to switch between character and word-based input, they have to go to settings and find the respective option there. Since the preference for char/word-based input can change quickly (do I want to write text or rather change text), I think it would be preferable to have a button in the function bar that does this.

Regards,
Tom

**Comment by shiftrot** [comment]
"Char/Word-based" is a setting to change only when the soft keyboard does not work properly.

**Comment by tomtom** [comment]
Ok, now I better understand how this is supposed to work and what doesn't work for me (see #8).
