### ISSUE TITLE
E326 Too many swap files found error

### ISSUE THREAD

**Issue by badger62** [shiftrot/droidvim#75]
I get this error when I create a new file . I think these are created by closing the shutting down the phone without saving the current unsaved buffer. I know what the solution is . Delete all the dead swap files .  I use an android phone . Where is the most likely location for all these swap files ?

**Comment by shiftrot** [comment]
See `:help :swapname`
```
The name of the swap file is normally the same as the file you are editing,
with the extension ".swp".
- On Unix, a '.' is prepended to swap file names in the same directory as the
  edited file.  This avoids that the swap file shows up in a directory
  listing.
```
