### ISSUE TITLE
FR: Improve word-based input

### ISSUE THREAD

**Issue by tomtom** [shiftrot/droidvim#8]
Hi!

In word-based input there is no way to easily "submit" a vim command to VIM.

Example: If users want to switch to insert mode and type "word", they have to type "iword". This breaks recommendation, correction etc. IMHO it would be preferable if there were a way to type "i" <SUBMIT> "word" instead -- whatever this SUBMIT is.

Regards,
Tom

**Comment by shiftrot** [comment]
You can use "◇" button to enable/disable word suggestion or use one-line textbox.
Also you can change input mode via Vimscript.
https://droidterm-e8a40.firebaseapp.com/droidvim/#h71

**Comment by tomtom** [comment]
> You can use "◇" button to enable/disable word suggestion or use 
one-line textbox.

Ok, now I understand better how it is intended to use this. I think my 
real problem is that in word-based mode, which is why I switched to 
char-based input, special characters in words (e.g. umlauts ä, ö, ü 
etc.) don't work. A word that contains such a character won't be 
inserted in word-based input mode.

**Comment by shiftrot** [comment]
Word correction is a soft keyboard dependent issue, and it is difficult to fix it with DroidVim.
See below.
https://droidterm-e8a40.firebaseapp.com/droidvim/#h50
