### ISSUE TITLE
Can't write file back to other app (content provider?)

### ISSUE THREAD

**Issue by ta765765** [shiftrot/droidvim#9]
If I select a file to open in my backup app (Tresorit) and then pick DroidVim, the file data gets to DroidVim but saving it back does not work.  This is possible at least in principle since KeePassDroid and QuickEdit can do it.

**Comment by shiftrot** [comment]
I suppose that this is a problem that Tresorit should fix, so please contact Tresorit's support.
It is easy to solve this problem from DroidVim side. So if Tresorit does not do anything to this problem, I will fix it on DroidVim side.
